#!/usr/bin/env bash
# Vendored-upstream Debian package build wrapper for f9dasm.
#
# Generated by the /package skill (~/.claude/skills/package/). This script is
# the entry point that foundry-apt's `build-all.sh` invokes:
#
#   1. Fetches the upstream source tarball (sha256-verified)
#   2. Extracts to a tmpdir
#   3. Copies our `debian/` tree into the upstream tree
#   4. Runs dpkg-buildpackage -us -uc -b
#   5. Moves the resulting .deb into $REPO_ROOT/dist/
#
# Build deps the CI runner needs (publish.yml installs these):
#   build-essential debhelper dpkg-dev lintian
#
# To bump the upstream version: change UPSTREAM_VERSION + SHA256 below, add
# a debian/changelog entry via `dch -v <NEW>-1foundry1 -D resolute`, re-pin
# the sha256 with:
#   curl -fsSL https://github.com/Arakula/f9dasm/archive/refs/tags/V<VER>.tar.gz | sha256sum

set -euo pipefail

for arg in "$@"; do
    case "$arg" in
        -h|--help)
            cat <<EOF
Build f9dasm as a Debian .deb via dpkg-buildpackage.

Usage: build.sh [-h|--help]

Environment overrides (rarely needed):
  F9DASM_VERSION    upstream version without the leading "V" (default: 1.83)
  F9DASM_SHA256     sha256 of the upstream tarball (must match VERSION)

Output: \$REPO_ROOT/dist/f9dasm_<UPSTREAM>-<REVISION>_<arch>.deb
EOF
            exit 0
            ;;
    esac
done

UPSTREAM_VERSION="${F9DASM_VERSION:-1.83}"
SHA256="${F9DASM_SHA256:-3a2d1e3f5de09be8060e4d754ff401622b5043b9a66687823fde188d035b0323}"
UPSTREAM_URL="https://github.com/Arakula/f9dasm/archive/refs/tags/V${UPSTREAM_VERSION}.tar.gz"

cd "$(dirname "$0")"
PKG_DIR="$(pwd)"
NAME="f9dasm"
REPO_ROOT="$(cd ../.. && pwd)"
mkdir -p "$REPO_ROOT/dist"

if ! curl -fsI -o /dev/null https://github.com/; then
    echo "ERROR: cannot reach github.com — skipping $NAME build" >&2
    exit 1
fi

WORKDIR=$(mktemp -d -t "${NAME}-build-XXXXXX")
trap "rm -rf '$WORKDIR'" EXIT

echo "=== Fetching $UPSTREAM_URL ==="
ORIG_TARBALL="$WORKDIR/${NAME}_${UPSTREAM_VERSION}.orig.tar.gz"
curl -fsSL -o "$ORIG_TARBALL" "$UPSTREAM_URL"

echo "=== Verifying sha256 ==="
echo "$SHA256  $ORIG_TARBALL" | sha256sum -c -

echo "=== Extracting ==="
tar -xzf "$ORIG_TARBALL" -C "$WORKDIR"
# GitHub's tarball strips a leading V/v from the tag → top dir is f9dasm-1.83/
SRC_DIR="$WORKDIR/${NAME}-${UPSTREAM_VERSION}"
[[ -d "$SRC_DIR" ]] || { echo "ERROR: expected $SRC_DIR after extract" >&2; ls "$WORKDIR"; exit 1; }

echo "=== Copying debian/ tree into source ==="
cp -a "$PKG_DIR/debian" "$SRC_DIR/"

echo "=== dpkg-buildpackage -us -uc -b ==="
( cd "$SRC_DIR" && dpkg-buildpackage -us -uc -b )

ARCH=$(dpkg --print-architecture)
REVISION=$(awk 'NR==1 {match($0, /\(([^)]+)\)/); print substr($0, RSTART+1, RLENGTH-2)}' "$PKG_DIR/debian/changelog" | sed "s/^${UPSTREAM_VERSION}-//")
DEB="$WORKDIR/${NAME}_${UPSTREAM_VERSION}-${REVISION}_${ARCH}.deb"
[[ -f "$DEB" ]] || { echo "ERROR: expected .deb not found: $DEB" >&2; ls -la "$WORKDIR"; exit 1; }

mv "$DEB" "$REPO_ROOT/dist/"
OUT="$REPO_ROOT/dist/$(basename "$DEB")"
echo "OK   $OUT  ($(stat -c%s "$OUT") bytes)"
