#!/usr/bin/env bash
# Vendored-upstream Debian package build wrapper for ppsspp.
#
# Generated by the /package skill (~/.claude/skills/package/).
#
# Unlike most packages in foundry-apt, this script does NOT download a tarball.
# GitHub's auto-generated tarballs for ppsspp lack git submodule content —
# ext/glslang, ext/SPIRV-Cross, ext/armips, and ext/cpu_features are empty.
# Instead, build.sh clones the repo at the pinned tag and initialises only
# those four submodules (depth 1), skipping the others which are replaced by
# system libraries via USE_SYSTEM_* cmake flags.
#
# Commit hash (v1.20.4): fa50bb1976065c4f8b1b47af227d367fe9771555
#
# Build deps the CI runner needs (publish.yml installs build-essential etc.;
# build.sh installs the package-specific deps listed below):
#   cmake pkg-config git
#   libsdl2-dev libgl-dev libglu-dev libsdl2-ttf-dev libfontconfig1-dev
#   libavcodec-dev libavformat-dev libavutil-dev libswscale-dev libswresample-dev
#   libvulkan-dev libpng-dev libsnappy-dev libzip-dev libzstd-dev
#   libminiupnpc-dev libfreetype-dev
#
# To bump the upstream version:
#   1. Update UPSTREAM_VERSION + EXPECTED_COMMIT below
#   2. Add a debian/changelog entry: dch -v <NEW>-1foundry1 -D resolute "Bump to <NEW>"
#   3. Verify the new commit hash: gh api repos/hrydgard/ppsspp/git/ref/tags/v<NEW>
#      then dereference the tag object to get the commit SHA

set -euo pipefail

for arg in "$@"; do
    case "$arg" in
        -h|--help)
            cat <<EOF
Build ppsspp as a Debian .deb via dpkg-buildpackage.

Usage: build.sh [-h|--help]

Environment overrides (rarely needed):
  PPSSPP_VERSION    upstream version without leading "v" (default: 1.20.4)
  PPSSPP_COMMIT     expected git commit SHA (must match version)

Output: \$REPO_ROOT/dist/ppsspp_<VERSION>-1foundry1_<arch>.deb
EOF
            exit 0
            ;;
    esac
done

UPSTREAM_VERSION="${PPSSPP_VERSION:-1.20.4}"
EXPECTED_COMMIT="${PPSSPP_COMMIT:-fa50bb1976065c4f8b1b47af227d367fe9771555}"
TAG="v${UPSTREAM_VERSION}"
REPO_URL="https://github.com/hrydgard/ppsspp.git"

cd "$(dirname "$0")"
PKG_DIR="$(pwd)"
NAME="ppsspp"
REPO_ROOT="$(cd ../.. && pwd)"
mkdir -p "$REPO_ROOT/dist"

if ! curl -fsI -o /dev/null https://github.com/; then
    echo "ERROR: cannot reach github.com — skipping $NAME build" >&2
    exit 1
fi

echo "=== Installing Build-Depends ==="
if command -v apt-get >/dev/null; then
    _apt() { [[ $EUID -eq 0 ]] && apt-get "$@" || sudo apt-get "$@"; }
    _apt install -y --no-install-recommends \
        cmake pkg-config git \
        libsdl2-dev libgl-dev libglu-dev libsdl2-ttf-dev libfontconfig1-dev \
        libavcodec-dev libavformat-dev libavutil-dev libavdevice-dev libswscale-dev libswresample-dev \
        libvulkan-dev libpng-dev libsnappy-dev libzip-dev libzstd-dev \
        libminiupnpc-dev libfreetype-dev libchdr-dev libopenxr-dev rapidjson-dev
fi

WORKDIR=$(mktemp -d -t "${NAME}-build-XXXXXX")
# shellcheck disable=SC2064
trap "rm -rf '$WORKDIR'" EXIT

SRC_DIR="$WORKDIR/${NAME}-${UPSTREAM_VERSION}"

echo "=== Cloning $REPO_URL at $TAG ==="
git clone --depth 1 --branch "$TAG" "$REPO_URL" "$SRC_DIR"

echo "=== Verifying commit hash ==="
ACTUAL_COMMIT=$(git -C "$SRC_DIR" rev-parse HEAD)
if [[ "$ACTUAL_COMMIT" != "$EXPECTED_COMMIT" ]]; then
    echo "ERROR: commit hash mismatch for $TAG:" >&2
    echo "  expected: $EXPECTED_COMMIT" >&2
    echo "  actual:   $ACTUAL_COMMIT" >&2
    echo "Update EXPECTED_COMMIT in build.sh if the tag was moved." >&2
    exit 1
fi
echo "Commit verified: $ACTUAL_COMMIT"

echo "=== Initialising required submodules (depth 1) ==="
# Only the four submodules that have no system-library substitute.
# ffmpeg, zstd, miniupnp, freetype, rapidjson, discord-rpc are replaced by
# system packages or disabled via USE_SYSTEM_*/USE_DISCORD cmake flags.
git -C "$SRC_DIR" submodule update --init --depth 1 \
    ext/glslang \
    ext/SPIRV-Cross \
    ext/cpu_features \
    ext/lua \
    ext/rcheevos \
    ext/aemu_postoffice \
    ext/nanosvg
# armips has its own sub-submodule (ext/filesystem); use --recursive for it
git -C "$SRC_DIR" submodule update --init --recursive --depth 1 \
    ext/armips

echo "=== Copying debian/ tree into source ==="
cp -a "$PKG_DIR/debian" "$SRC_DIR/"

echo "=== dpkg-buildpackage -us -uc -b ==="
( cd "$SRC_DIR" && dpkg-buildpackage -us -uc -b )

ARCH=$(dpkg --print-architecture)
DEB_VERSION=$(sed -n '1s/.*(\(.*\)).*/\1/p' "$PKG_DIR/debian/changelog")
DEB="$WORKDIR/${NAME}_${DEB_VERSION}_${ARCH}.deb"
[[ -f "$DEB" ]] || {
    echo "ERROR: expected .deb not found: $DEB" >&2
    ls -la "$WORKDIR"
    exit 1
}

mv "$DEB" "$REPO_ROOT/dist/"
OUT="$REPO_ROOT/dist/$(basename "$DEB")"
echo "OK   $OUT  ($(stat -c%s "$OUT") bytes)"
