#!/usr/bin/env bash
# Vendored-upstream Debian package build wrapper for wla-dx.
#
# Generated by the /package skill (~/.claude/skills/package/).
#
# Fetches the upstream tarball (sha256-pinned), overlays debian/, and builds
# a .deb via dpkg-buildpackage. No external build deps beyond cmake.
#
# Tag:   v10.6
# SHA256 sourced: 2026-06-11
#
# To bump the upstream version:
#   1. Update UPSTREAM_VERSION + EXPECTED_SHA256 below
#   2. Add a debian/changelog entry:
#        dch -v <NEW>-1foundry1 -D resolute "Bump to <NEW>"
#   3. Re-pin: curl -fsSL <tarball-url> | sha256sum

set -euo pipefail

for arg in "$@"; do
    case "$arg" in
        -h|--help)
            cat <<EOF
Build wla-dx as a Debian .deb via dpkg-buildpackage.

Usage: build.sh [-h|--help]

Output: \$REPO_ROOT/dist/wla-dx_<VERSION>-1foundry1_<arch>.deb
EOF
            exit 0
            ;;
    esac
done

UPSTREAM_VERSION="${WLA_DX_VERSION:-10.6}"
EXPECTED_SHA256="${WLA_DX_SHA256:-010c4d426fd1733b978cbca7530a5e68bdfb6f62976c0d5ff7bff447894e19a8}"
TARBALL_URL="https://github.com/vhelin/wla-dx/archive/refs/tags/v${UPSTREAM_VERSION}.tar.gz"

cd "$(dirname "$0")"
PKG_DIR="$(pwd)"
NAME="wla-dx"
REPO_ROOT="$(cd ../.. && pwd)"
mkdir -p "$REPO_ROOT/dist"

if ! curl -fsI -o /dev/null https://github.com/; then
    echo "ERROR: cannot reach github.com — skipping $NAME build" >&2
    exit 1
fi

echo "=== Installing Build-Depends ==="
if command -v apt-get >/dev/null; then
    _apt() { [[ $EUID -eq 0 ]] && apt-get "$@" || sudo apt-get "$@"; }
    _apt install -y --no-install-recommends cmake
fi

WORKDIR=$(mktemp -d -t "${NAME}-build-XXXXXX")
# shellcheck disable=SC2064
trap "rm -rf '$WORKDIR'" EXIT

echo "=== Downloading $TARBALL_URL ==="
curl -fsSL -o "$WORKDIR/upstream.tar.gz" "$TARBALL_URL"

echo "=== Verifying SHA256 ==="
ACTUAL_SHA256=$(sha256sum "$WORKDIR/upstream.tar.gz" | awk '{print $1}')
if [[ "$ACTUAL_SHA256" != "$EXPECTED_SHA256" ]]; then
    echo "ERROR: SHA256 mismatch for ${UPSTREAM_VERSION} tarball:" >&2
    echo "  expected: $EXPECTED_SHA256" >&2
    echo "  actual:   $ACTUAL_SHA256" >&2
    echo "Update EXPECTED_SHA256 in build.sh if upstream re-released the tag." >&2
    exit 1
fi
echo "SHA256 verified: $ACTUAL_SHA256"

echo "=== Extracting tarball ==="
tar -xzf "$WORKDIR/upstream.tar.gz" -C "$WORKDIR"
# GitHub extracts as wla-dx-<version>/
SRC_DIR="$WORKDIR/wla-dx-${UPSTREAM_VERSION}"
[[ -d "$SRC_DIR" ]] || {
    echo "ERROR: expected source dir not found: $SRC_DIR" >&2
    ls "$WORKDIR"
    exit 1
}

echo "=== Copying debian/ tree into source ==="
cp -a "$PKG_DIR/debian" "$SRC_DIR/"

echo "=== dpkg-buildpackage -us -uc -b ==="
( cd "$SRC_DIR" && dpkg-buildpackage -us -uc -b )

ARCH=$(dpkg --print-architecture)
DEB_VERSION=$(sed -n '1s/.*(\(.*\)).*/\1/p' "$PKG_DIR/debian/changelog")
DEB="$WORKDIR/${NAME}_${DEB_VERSION}_${ARCH}.deb"
[[ -f "$DEB" ]] || {
    echo "ERROR: expected .deb not found: $DEB" >&2
    ls -la "$WORKDIR"
    exit 1
}

mv "$DEB" "$REPO_ROOT/dist/"
OUT="$REPO_ROOT/dist/$(basename "$DEB")"
echo "OK   $OUT  ($(stat -c%s "$OUT") bytes)"
