#!/usr/bin/env bash
# Vendored-upstream Debian package build wrapper for Tilemap Studio.
#
# Generated by the /package skill (~/.claude/skills/package/). Unlike a typical
# foundry vendored upstream this fetches TWO sha256-pinned tarballs:
#
#   1. Tilemap Studio source (the package)
#   2. FLTK 1.4.5 source — placed in lib/fltk so debian/rules can build it
#      X11-only and static-link it (Ubuntu 26.04 ships FLTK 1.4.4 as a
#      Wayland-hybrid build that upstream's X11 window code won't compile
#      against). See debian/rules for the cmake flags.
#
# Steps: fetch + verify both tarballs -> overlay debian/ -> apply Perl patches
# (GNU patch 2.8 fails on CRLF upstream sources; perl -i -0pe handles CRLF
# transparently) -> dpkg-buildpackage -> move the .deb into $REPO_ROOT/dist/.
# Patches are documented in debian/patches/. 0001 is already in upstream master
# (commit ffcce44); only needed while packaging the v4.0.1 release tarball.
#
# To bump: change *_VERSION + *_SHA256 below, add a debian/changelog entry via
#   dch -v <NEW>-1foundry1 -D resolute "..."
# and re-pin with:
#   curl -fsSL <url> | sha256sum

set -euo pipefail

for arg in "$@"; do
    case "$arg" in
        -h|--help)
            cat <<EOF
Build Tilemap Studio (with static FLTK 1.4.5) as a Debian .deb.

Usage: build.sh [-h|--help]

Output: \$REPO_ROOT/dist/tilemap-studio_<UPSTREAM>-<REVISION>_<arch>.deb
EOF
            exit 0
            ;;
    esac
done

UPSTREAM_VERSION="${TILEMAP_VERSION:-4.0.1}"
SHA256="${TILEMAP_SHA256:-aba346519dc3be7f46bacdd481fa7fce61c187032544593c78d1e40c98210c97}"
UPSTREAM_URL="https://github.com/Rangi42/tilemap-studio/archive/refs/tags/v${UPSTREAM_VERSION}.tar.gz"

FLTK_VERSION="${FLTK_VERSION:-1.4.5}"
FLTK_SHA256="${FLTK_SHA256:-7715e69ce081fa9ce6da48bb0dd3b07a4cf2cf937813814c04272f36fff593ea}"
FLTK_URL="https://github.com/fltk/fltk/archive/refs/tags/release-${FLTK_VERSION}.tar.gz"

cd "$(dirname "$0")"
PKG_DIR="$(pwd)"
NAME="tilemap-studio"
REPO_ROOT="$(cd ../.. && pwd)"
mkdir -p "$REPO_ROOT/dist"

# Install package-specific Build-Depends (CI installs build-essential/debhelper
# globally; these are the rest from debian/control). Root in Docker, sudo on the
# GitHub runner.
if command -v apt-get >/dev/null; then
    # shellcheck disable=SC2015  # root path runs apt-get; non-root falls back to sudo
    _apt() { [[ $EUID -eq 0 ]] && apt-get "$@" || sudo apt-get "$@"; }
    _apt install -y --no-install-recommends \
        cmake pkg-config zlib1g-dev libpng-dev libjpeg-dev libxpm-dev libx11-dev \
        libxft-dev libxinerama-dev libfontconfig1-dev libxext-dev libxrender-dev \
        libxfixes-dev libcairo2-dev libpango1.0-dev \
        libwayland-dev wayland-protocols libxkbcommon-dev libxcursor-dev libdecor-0-dev \
        libwayland-egl-backend-dev libegl-dev libgl-dev libglu1-mesa-dev \
        libgtk-3-dev >/dev/null
fi

if ! curl -fsI -o /dev/null https://github.com/; then
    echo "ERROR: cannot reach github.com — skipping $NAME build" >&2
    exit 1
fi

WORKDIR=$(mktemp -d -t "${NAME}-build-XXXXXX")
# shellcheck disable=SC2064
trap "rm -rf '$WORKDIR'" EXIT

echo "=== Fetching $UPSTREAM_URL ==="
ORIG_TARBALL="$WORKDIR/${NAME}_${UPSTREAM_VERSION}.orig.tar.gz"
curl -fsSL -o "$ORIG_TARBALL" "$UPSTREAM_URL"
echo "$SHA256  $ORIG_TARBALL" | sha256sum -c -

echo "=== Fetching $FLTK_URL ==="
FLTK_TARBALL="$WORKDIR/fltk.tar.gz"
curl -fsSL -o "$FLTK_TARBALL" "$FLTK_URL"
echo "$FLTK_SHA256  $FLTK_TARBALL" | sha256sum -c -

echo "=== Extracting ==="
tar -xzf "$ORIG_TARBALL" -C "$WORKDIR"
SRC_DIR="$WORKDIR/${NAME}-${UPSTREAM_VERSION}"
[[ -d "$SRC_DIR" ]] || { echo "ERROR: expected $SRC_DIR after extract" >&2; ls "$WORKDIR"; exit 1; }

# Place FLTK source where debian/rules expects it (lib/fltk).
mkdir -p "$SRC_DIR/lib"
tar -xzf "$FLTK_TARBALL" -C "$SRC_DIR/lib"
mv "$SRC_DIR/lib/fltk-release-${FLTK_VERSION}" "$SRC_DIR/lib/fltk"

echo "=== Copying debian/ tree into source ==="
cp -a "$PKG_DIR/debian" "$SRC_DIR/"

# dpkg-source --before-build doesn't apply patches when debian/ is overlaid on
# a fresh extract. GNU patch 2.8 also fails on CRLF sources. Apply via perl so
# patches are in place before dpkg-buildpackage sees the tree.
echo "=== Applying patches ==="
# GNU patch 2.8 has fundamental CRLF handling issues; quilt is also unreliable
# when debian/ is overlaid on a manually extracted tree. Apply via perl, which
# handles CRLF transparently and preserves the upstream encoding in output.
# Patches are documented in debian/patches/ and forwarded upstream as PR #95.
#
# 0001: add FL/platform.H to main-window.h so Pixmap / fl_display / fl_xid
#       are declared in FLTK 1.4.5 Wayland+X11 hybrid builds (they no longer
#       leak through transitive FLTK headers as they did in X11-only mode).
#       Already in upstream master (ffcce44); not yet in v4.0.1.
perl -i -0pe 's{(#include <FL/Fl_Native_File_Chooser\.H>)(\r?\n)}{$1$2#include <FL/platform.H>$2}' \
    "$SRC_DIR/src/main-window.h"
grep -q "platform.H" "$SRC_DIR/src/main-window.h" \
    || { echo "ERROR: patch 0001 failed (platform.H not found)" >&2; exit 1; }
#
# 0002: add <cstring> to preferences.cpp (strcpy/strcat not declared in
#       GCC 15 without it after FLTK 1.4.5 removed the transitive include).
perl -i -0pe 's{(#pragma warning\(push, 0\))(\r?\n)(#include <FL/Fl_Preferences\.H>)}{$1$2#include <cstring>$2$3}' \
    "$SRC_DIR/src/preferences.cpp"
grep -q "cstring" "$SRC_DIR/src/preferences.cpp" \
    || { echo "ERROR: patch 0002 failed (cstring not found)" >&2; exit 1; }
echo "  0001-platform-h-in-main-window — applied"
echo "  0002-cstring-in-preferences — applied"

echo "=== dpkg-buildpackage -us -uc -b ==="
# Emit the source package (.dsc + tarballs) -> dist/ for the apt Sources index
# (best-effort; never blocks the binary build below). See scripts/lib-source-build.sh.
if [[ -f "$REPO_ROOT/scripts/lib-source-build.sh" ]]; then
    # shellcheck source=/dev/null
    source "$REPO_ROOT/scripts/lib-source-build.sh"
    emit_source_package "$SRC_DIR" "$WORKDIR" "$REPO_ROOT" || true
fi
( cd "$SRC_DIR" && dpkg-buildpackage -us -uc -b )

ARCH=$(dpkg --print-architecture)
REVISION=$(sed -n '1s/.*(\(.*\)).*/\1/p' "$PKG_DIR/debian/changelog" | sed "s/^${UPSTREAM_VERSION}-//")
DEB="$WORKDIR/${NAME}_${UPSTREAM_VERSION}-${REVISION}_${ARCH}.deb"
[[ -f "$DEB" ]] || { echo "ERROR: expected .deb not found: $DEB" >&2; ls -la "$WORKDIR"; exit 1; }

mv "$DEB" "$REPO_ROOT/dist/"
OUT="$REPO_ROOT/dist/$(basename "$DEB")"
echo "OK   $OUT  ($(stat -c%s "$OUT") bytes)"
