#!/usr/bin/env bash
# Vendored-upstream Debian package build wrapper for snes9x-gtk.
#
# Generated by the /package skill (~/.claude/skills/package/).
#
# Downloads the upstream tarball (sha256-pinned); no submodules required
# when USE_SLANG=OFF (only glslang/SPIRV-Cross/vulkan-headers submodules
# are needed for Vulkan shader support, which we disable).
#
# Tag: 1.63 (no leading "v")
# Commit: 921f9f7b83660eb44ad263022a57a4a029057c37
#
# Build deps the CI runner needs:
#   cmake pkg-config gettext
#   libgtkmm-3.0-dev libsdl2-dev libpng-dev libxrandr-dev
#   libx11-dev libxext-dev libpulse-dev libasound2-dev
#   portaudio19-dev zlib1g-dev libminizip-dev
#
# To bump the upstream version:
#   1. Update UPSTREAM_VERSION + SHA256 below
#   2. Add a debian/changelog entry: dch -v <NEW>-1foundry1 -D stable "Bump to <NEW>"
#   3. Verify SHA256: curl -fsSL <tarball-url> | sha256sum

set -euo pipefail

for arg in "$@"; do
    case "$arg" in
        -h|--help)
            cat <<EOF
Build snes9x-gtk as a Debian .deb via dpkg-buildpackage.

Usage: build.sh [-h|--help]

Environment overrides (rarely needed):
  SNES9X_VERSION    upstream version (default: 1.63)
  SNES9X_SHA256     expected sha256 of upstream tarball

Output: \$REPO_ROOT/dist/snes9x-gtk_<VERSION>-1foundry1_<arch>.deb
EOF
            exit 0
            ;;
    esac
done

UPSTREAM_VERSION="${SNES9X_VERSION:-1.63}"
EXPECTED_SHA256="${SNES9X_SHA256:-84560ce38a734ac8299645883d8e0c0423b7da2430bde5f88276bba1be6d5330}"
TARBALL_URL="https://github.com/snes9xgit/snes9x/archive/refs/tags/${UPSTREAM_VERSION}.tar.gz"

cd "$(dirname "$0")"
PKG_DIR="$(pwd)"
NAME="snes9x-gtk"
UPSTREAM_NAME="snes9x"
REPO_ROOT="$(cd ../.. && pwd)"
mkdir -p "$REPO_ROOT/dist"

if ! curl -fsI -o /dev/null https://github.com/; then
    echo "ERROR: cannot reach github.com — skipping $NAME build" >&2
    exit 1
fi

echo "=== Installing Build-Depends ==="
if command -v apt-get >/dev/null; then
    _apt() { [[ $EUID -eq 0 ]] && apt-get "$@" || sudo apt-get "$@"; }
    _apt install -y --no-install-recommends \
        cmake pkg-config gettext \
        libgtkmm-3.0-dev libsdl2-dev libpng-dev libxrandr-dev \
        libx11-dev libxext-dev libpulse-dev libasound2-dev \
        portaudio19-dev zlib1g-dev libminizip-dev
fi

WORKDIR=$(mktemp -d -t "${NAME}-build-XXXXXX")
# shellcheck disable=SC2064
trap "rm -rf '$WORKDIR'" EXIT

echo "=== Downloading $TARBALL_URL ==="
curl -fsSL -o "$WORKDIR/upstream.tar.gz" "$TARBALL_URL"

echo "=== Verifying SHA256 ==="
ACTUAL_SHA256=$(sha256sum "$WORKDIR/upstream.tar.gz" | awk '{print $1}')
if [[ "$ACTUAL_SHA256" != "$EXPECTED_SHA256" ]]; then
    echo "ERROR: SHA256 mismatch for $UPSTREAM_VERSION tarball:" >&2
    echo "  expected: $EXPECTED_SHA256" >&2
    echo "  actual:   $ACTUAL_SHA256" >&2
    echo "Update EXPECTED_SHA256 in build.sh if upstream re-released the tag." >&2
    exit 1
fi
echo "SHA256 verified: $ACTUAL_SHA256"

echo "=== Extracting tarball ==="
tar -xzf "$WORKDIR/upstream.tar.gz" -C "$WORKDIR"
# GitHub extracts as snes9x-<version>/
SRC_DIR="$WORKDIR/${UPSTREAM_NAME}-${UPSTREAM_VERSION}"

echo "=== Copying debian/ tree into source ==="
cp -a "$PKG_DIR/debian" "$SRC_DIR/"

echo "=== dpkg-buildpackage -us -uc -b ==="
( cd "$SRC_DIR" && dpkg-buildpackage -us -uc -b )

ARCH=$(dpkg --print-architecture)
DEB_VERSION=$(sed -n '1s/.*(\(.*\)).*/\1/p' "$PKG_DIR/debian/changelog")
DEB="$WORKDIR/${NAME}_${DEB_VERSION}_${ARCH}.deb"
[[ -f "$DEB" ]] || {
    echo "ERROR: expected .deb not found: $DEB" >&2
    ls -la "$WORKDIR"
    exit 1
}

mv "$DEB" "$REPO_ROOT/dist/"
OUT="$REPO_ROOT/dist/$(basename "$DEB")"
echo "OK   $OUT  ($(stat -c%s "$OUT") bytes)"
