#!/usr/bin/env bash
# Vendored-upstream Debian package build wrapper for m8te.
#
# Generated by the /package skill (~/.claude/skills/package/). foundry-apt's
# scripts/build-all.sh invokes this script. It:
#
#   1. Fetches the upstream tag-1.5 source tarball (sha256-verified)
#   2. Extracts and normalizes the top dir to m8te-<VERSION>/
#   3. Installs package-specific Build-Depends (icoutils)
#   4. Copies our debian/ tree into the source
#   5. Runs dpkg-buildpackage -us -uc -b (binary-only; Architecture: all)
#   6. Moves the resulting _all.deb into $REPO_ROOT/dist/
#
# M8TE is a Mono/.NET WinForms app: upstream ships a pre-built CIL assembly
# (bin/Release/M8TE.exe), so there is no compile step — debian/rules just
# installs the assembly and a mono wrapper. The committed bin/Release/M8TE.exe
# inside this tarball is byte-identical to the official 1.5 release download
# (sha256 f6470bfa7315b44bbc5ac75d7959155ffbe03fc92ef5b05f47e2a66f8dbcaa94).
#
# To bump the upstream version: change UPSTREAM_VERSION + SHA256 below, add a
# debian/changelog entry via `dch -v <NEW>-1foundry1 -D resolute`, and re-pin:
#   curl -fsSL https://github.com/nesdoug/M8TE/archive/refs/tags/<VER>.tar.gz | sha256sum

set -euo pipefail

for arg in "$@"; do
    case "$arg" in
        -h|--help)
            cat <<EOF
Build m8te as a Debian .deb via dpkg-buildpackage.

Usage: build.sh [-h|--help]

Environment overrides (rarely needed):
  M8TE_VERSION    upstream version (default: 1.5)
  M8TE_SHA256     sha256 of the upstream tarball (must match VERSION)

Output: \$REPO_ROOT/dist/m8te_<DEB_VERSION>_all.deb
EOF
            exit 0
            ;;
    esac
done

UPSTREAM_VERSION="${M8TE_VERSION:-1.5}"
SHA256="${M8TE_SHA256:-0c72a643ef857308614a709882e39d2d00685e931f1f0d40aeedc14f50ebd6be}"
UPSTREAM_URL="https://github.com/nesdoug/M8TE/archive/refs/tags/${UPSTREAM_VERSION}.tar.gz"

cd "$(dirname "$0")"
PKG_DIR="$(pwd)"
NAME="m8te"
REPO_ROOT="$(cd ../.. && pwd)"
mkdir -p "$REPO_ROOT/dist"

if ! curl -fsI -o /dev/null https://github.com/; then
    echo "ERROR: cannot reach github.com — skipping $NAME build" >&2
    exit 1
fi

WORKDIR=$(mktemp -d -t "${NAME}-build-XXXXXX")
# shellcheck disable=SC2064  # expand $WORKDIR now so the trap captures the value
trap "rm -rf '$WORKDIR'" EXIT

echo "=== Fetching $UPSTREAM_URL ==="
ORIG_TARBALL="$WORKDIR/${NAME}_${UPSTREAM_VERSION}.orig.tar.gz"
curl -fsSL -o "$ORIG_TARBALL" "$UPSTREAM_URL"

echo "=== Verifying sha256 ==="
echo "$SHA256  $ORIG_TARBALL" | sha256sum -c -

echo "=== Extracting ==="
tar -xzf "$ORIG_TARBALL" -C "$WORKDIR"
# GitHub's archive for tag 1.5 unpacks to M8TE-1.5/ — normalize to m8te-1.5/.
SRC_DIR="$WORKDIR/${NAME}-${UPSTREAM_VERSION}"
EXTRACTED=$(find "$WORKDIR" -mindepth 1 -maxdepth 1 -type d -print -quit)
[[ -n "$EXTRACTED" ]] || { echo "ERROR: no extracted dir under $WORKDIR" >&2; exit 1; }
[[ "$EXTRACTED" == "$SRC_DIR" ]] || mv "$EXTRACTED" "$SRC_DIR"

echo "=== Installing Build-Depends ==="
if command -v apt-get >/dev/null; then
    # shellcheck disable=SC2015  # root path runs apt-get; non-root falls back to sudo
    _apt() { [[ $EUID -eq 0 ]] && apt-get "$@" || sudo apt-get "$@"; }
    _apt install -y --no-install-recommends icoutils
fi

echo "=== Copying debian/ tree into source ==="
cp -a "$PKG_DIR/debian" "$SRC_DIR/"

echo "=== dpkg-buildpackage -us -uc -b ==="
( cd "$SRC_DIR" && dpkg-buildpackage -us -uc -b )

# Architecture: all -> the artifact is m8te_<DEB_VERSION>_all.deb. Use sed
# (mawk-safe; the 3-arg awk match() needs gawk) to read the changelog version,
# then glob the arch suffix.
DEB_VERSION=$(sed -n '1s/.*(\(.*\)).*/\1/p' "$PKG_DIR/debian/changelog")
# shellcheck disable=SC2012  # controlled dist filenames (name_version_arch.deb); ls is safe
DEB=$(ls "$WORKDIR/${NAME}_${DEB_VERSION}_"*.deb 2>/dev/null | head -1 || true)
[[ -n "$DEB" && -f "$DEB" ]] || { echo "ERROR: expected .deb not found for ${NAME}_${DEB_VERSION}" >&2; ls -la "$WORKDIR"; exit 1; }

mv "$DEB" "$REPO_ROOT/dist/"
OUT="$REPO_ROOT/dist/$(basename "$DEB")"
echo "OK   $OUT  ($(stat -c%s "$OUT") bytes)"
