#!/usr/bin/env bash
# Vendored-upstream Debian package build wrapper for vgmstream.
#
# Generated by the /package skill (~/.claude/skills/package/). This script is
# the entry point that foundry-apt's `build-all.sh` invokes:
#
#   1. Fetches the upstream source tarball (sha256-verified)
#   2. Extracts to a tmpdir
#   3. Copies our `debian/` tree into the upstream tree
#   4. Runs dpkg-buildpackage -us -uc -b
#   5. Moves the resulting .deb into $REPO_ROOT/dist/
#
# Build deps the CI runner needs (publish.yml installs these):
#   build-essential debhelper dpkg-dev lintian pkg-config cmake yasm
#   libmpg123-dev libvorbis-dev libspeex-dev libopus-dev
#   libavformat-dev libavcodec-dev libavutil-dev libswresample-dev
#
# To bump the upstream version: change UPSTREAM_VERSION + SHA256 below, add
# a debian/changelog entry via `dch -v <NEW>-1foundry1 -D resolute`, re-pin
# the sha256 with:
#   curl -fsSL https://github.com/vgmstream/vgmstream/archive/refs/tags/r<VER>.tar.gz | sha256sum

set -euo pipefail

for arg in "$@"; do
    case "$arg" in
        -h|--help)
            cat <<EOF
Build vgmstream as a Debian .deb via dpkg-buildpackage.

Usage: build.sh [-h|--help]

Environment overrides (rarely needed):
  VGMSTREAM_VERSION  upstream version without the leading "r" (default: 2083)
  VGMSTREAM_SHA256   sha256 of the upstream tarball (must match VERSION)

Output: \$REPO_ROOT/dist/vgmstream_<DEB_VERSION>_<arch>.deb
EOF
            exit 0
            ;;
    esac
done

UPSTREAM_VERSION="${VGMSTREAM_VERSION:-2083}"
SHA256="${VGMSTREAM_SHA256:-22cec642df2ea4148849d64d5af384f156a1dbebd95567e00236833dd9dbe136}"
UPSTREAM_URL="https://github.com/vgmstream/vgmstream/archive/refs/tags/r${UPSTREAM_VERSION}.tar.gz"

cd "$(dirname "$0")"
PKG_DIR="$(pwd)"
NAME="vgmstream"
REPO_ROOT="$(cd ../.. && pwd)"
mkdir -p "$REPO_ROOT/dist"

if ! curl -fsI -o /dev/null https://github.com/; then
    echo "ERROR: cannot reach github.com — skipping $NAME build" >&2
    exit 1
fi

WORKDIR=$(mktemp -d -t "${NAME}-build-XXXXXX")
# shellcheck disable=SC2064  # expand $WORKDIR now so the trap captures the value
trap "rm -rf '$WORKDIR'" EXIT

echo "=== Fetching $UPSTREAM_URL ==="
ORIG_TARBALL="$WORKDIR/${NAME}_r${UPSTREAM_VERSION}.orig.tar.gz"
curl -fsSL -o "$ORIG_TARBALL" "$UPSTREAM_URL"

echo "=== Verifying sha256 ==="
echo "$SHA256  $ORIG_TARBALL" | sha256sum -c -

echo "=== Extracting ==="
tar -xzf "$ORIG_TARBALL" -C "$WORKDIR"
SRC_DIR="$WORKDIR/${NAME}-r${UPSTREAM_VERSION}"
[[ -d "$SRC_DIR" ]] || { echo "ERROR: expected $SRC_DIR after extract" >&2; ls "$WORKDIR"; exit 1; }

echo "=== Copying debian/ tree into source ==="
cp -a "$PKG_DIR/debian" "$SRC_DIR/"

echo "=== Installing Build-Depends ==="
if command -v apt-get >/dev/null; then
    _apt() { if [[ $EUID -eq 0 ]]; then apt-get "$@"; else sudo apt-get "$@"; fi; }
    _apt install -y --no-install-recommends \
        cmake yasm libmpg123-dev libvorbis-dev libspeex-dev libopus-dev \
        libavcodec-dev libavformat-dev libavutil-dev libswresample-dev
fi

echo "=== dpkg-buildpackage -us -uc -b ==="
( cd "$SRC_DIR" && dpkg-buildpackage -us -uc -b )

ARCH=$(dpkg --print-architecture)
DEB_VERSION=$(awk 'NR==1 {match($0, /\(([^)]+)\)/); print substr($0, RSTART+1, RLENGTH-2)}' "$PKG_DIR/debian/changelog")
DEB="$WORKDIR/${NAME}_${DEB_VERSION}_${ARCH}.deb"
[[ -f "$DEB" ]] || { echo "ERROR: expected .deb not found: $DEB" >&2; ls -la "$WORKDIR"; exit 1; }

mv "$DEB" "$REPO_ROOT/dist/"
OUT="$REPO_ROOT/dist/$(basename "$DEB")"
echo "OK   $OUT  ($(stat -c%s "$OUT") bytes)"
