#!/usr/bin/env bash
# Vendored-upstream Debian package build wrapper for libvgm.
#
# Generated by the /package skill (~/.claude/skills/package/). This script is
# the entry point that foundry-apt's `build-all.sh` invokes:
#
#   1. Fetches the upstream source tarball (sha256-verified)
#   2. Extracts to a tmpdir
#   3. Copies our `debian/` tree into the upstream tree
#   4. Runs dpkg-buildpackage -us -uc -b
#   5. Moves the resulting .deb into $REPO_ROOT/dist/
#
# Build deps the CI runner needs (publish.yml installs these):
#   build-essential debhelper dpkg-dev cmake pkg-config lintian
#   zlib1g-dev libasound2-dev libpulse-dev libao-dev
#
# libvgm has no tagged upstream releases — packaging is pinned to a specific
# commit by sha256. To bump:
#   1. Pick a new master commit:
#      gh api repos/ValleyBell/libvgm/commits/master --jq .sha
#   2. Update UPSTREAM_COMMIT + UPSTREAM_DATE (YYYYMMDD) below.
#   3. Re-pin the sha256:
#      curl -fsSL https://github.com/ValleyBell/libvgm/archive/<sha>.tar.gz \
#        | sha256sum
#      update SHA256 below.
#   4. Bump debian/changelog via:
#      dch -v "0.1+git${UPSTREAM_DATE}.${UPSTREAM_COMMIT:0:7}-1foundry<N>" \
#          -D resolute "Bump to upstream master <sha-short> (<date>)"

set -euo pipefail

for arg in "$@"; do
    case "$arg" in
        -h|--help)
            cat <<EOF
Build libvgm as a Debian .deb via dpkg-buildpackage.

Usage: build.sh [-h|--help]

Environment overrides (rarely needed):
  LIBVGM_COMMIT   upstream commit sha (default: d1151884997ba4769b070b7c7aaedeffc60a25fb)
  LIBVGM_DATE     upstream commit date as YYYYMMDD (default: 20260406)
  LIBVGM_SHA256   sha256 of the upstream tarball (must match COMMIT)

Output: \$REPO_ROOT/dist/libvgm_<UPSTREAM>-<REVISION>_<arch>.deb
EOF
            exit 0
            ;;
    esac
done

UPSTREAM_COMMIT="${LIBVGM_COMMIT:-d1151884997ba4769b070b7c7aaedeffc60a25fb}"
UPSTREAM_DATE="${LIBVGM_DATE:-20260406}"
SHA256="${LIBVGM_SHA256:-7af2e58bc1bef990c0ee759cdef7bdf5e1e1ebc9d16cde489932b0370c0e7fbc}"

# Synthesised upstream version string: 0.1 (upstream's declared CMake version)
# + git-snapshot qualifier so versions sort correctly across rebumps.
UPSTREAM_VERSION="0.1+git${UPSTREAM_DATE}.${UPSTREAM_COMMIT:0:7}"
UPSTREAM_URL="https://github.com/ValleyBell/libvgm/archive/${UPSTREAM_COMMIT}.tar.gz"

cd "$(dirname "$0")"
PKG_DIR="$(pwd)"
NAME="libvgm"
REPO_ROOT="$(cd ../.. && pwd)"
mkdir -p "$REPO_ROOT/dist"

if ! curl -fsI -o /dev/null https://github.com/; then
    echo "ERROR: cannot reach github.com — skipping $NAME build" >&2
    exit 1
fi

WORKDIR=$(mktemp -d -t "${NAME}-build-XXXXXX")
# shellcheck disable=SC2064  # expand $WORKDIR now so the trap captures the value
trap "rm -rf '$WORKDIR'" EXIT

echo "=== Fetching $UPSTREAM_URL ==="
ORIG_TARBALL="$WORKDIR/${NAME}_${UPSTREAM_VERSION}.orig.tar.gz"
curl -fsSL -o "$ORIG_TARBALL" "$UPSTREAM_URL"

echo "=== Verifying sha256 ==="
echo "$SHA256  $ORIG_TARBALL" | sha256sum -c -

echo "=== Extracting ==="
tar -xzf "$ORIG_TARBALL" -C "$WORKDIR"
# GitHub commit-sha archive extracts to libvgm-<full-sha>/ ; rename to the
# canonical dpkg-buildpackage <name>-<version>/ form.
SRC_DIR="$WORKDIR/${NAME}-${UPSTREAM_VERSION}"
mv "$WORKDIR/${NAME}-${UPSTREAM_COMMIT}" "$SRC_DIR"

echo "=== Copying debian/ tree into source ==="
cp -a "$PKG_DIR/debian" "$SRC_DIR/"

echo "=== Installing Build-Depends ==="
if [[ $EUID -eq 0 ]] && command -v apt-get >/dev/null; then
    apt-get install -y --no-install-recommends \
        cmake pkg-config zlib1g-dev libasound2-dev libpulse-dev libao-dev
fi

echo "=== dpkg-buildpackage -us -uc -b ==="
( cd "$SRC_DIR" && dpkg-buildpackage -us -uc -b )

ARCH=$(dpkg --print-architecture)
REVISION=$(awk 'NR==1 {match($0, /\(([^)]+)\)/); print substr($0, RSTART+1, RLENGTH-2)}' "$PKG_DIR/debian/changelog" | sed "s/^${UPSTREAM_VERSION}-//")
DEB="$WORKDIR/${NAME}_${UPSTREAM_VERSION}-${REVISION}_${ARCH}.deb"
[[ -f "$DEB" ]] || { echo "ERROR: expected .deb not found: $DEB" >&2; ls -la "$WORKDIR"; exit 1; }

mv "$DEB" "$REPO_ROOT/dist/"
OUT="$REPO_ROOT/dist/$(basename "$DEB")"
echo "OK   $OUT  ($(stat -c%s "$OUT") bytes)"
