#!/usr/bin/env bash
# Vendored-upstream Debian package build wrapper for flycast (Sega Dreamcast,
# NAOMI and Atomiswave emulator).
#
# Generated by the /package skill (~/.claude/skills/package/).
#
# Like ppsspp — and unlike most packages in foundry-apt — this script does NOT
# download a tarball. Neither of the usual vendoring routes works for Flycast:
#
#   * GitHub's auto-generated tag archive omits all 20 git submodules under
#     core/deps/ (Vulkan-Headers, VulkanMemoryAllocator, glslang, libchdr,
#     libjuice, luabridge, rcheevos, asio, websocketpp, xbyak, ...), so it will
#     not configure, let alone build.
#   * Upstream publishes no source release asset. The v2.6 release carries only
#     binaries (.apk, .appx, .nro, macOS .zip, win64 .zip, x86_64.AppImage).
#
# So we clone at the pinned tag and assert the commit SHA. That is not a weaker
# guarantee than a tarball sha256 — it is a stronger one. A git commit SHA is a
# hash over the whole tree, and every submodule is recorded in that tree as a
# gitlink naming the submodule's own commit SHA. Pinning the superproject
# commit therefore transitively pins all 20 submodules, and git verifies each
# on checkout.
#
# Do NOT switch this to `git clone --recurse-submodules --shallow-submodules`:
# a shallow submodule fetch can land on the submodule's branch tip rather than
# the recorded commit, silently breaking the pin. The explicit
# `git submodule update --init --depth 1 <paths>` below fetches each recorded
# SHA by name.
#
# Build deps the CI runner needs (publish.yml installs build-essential etc.;
# build.sh installs the package-specific deps listed below):
#   cmake pkgconf git
#   libsdl2-dev libcurl4-gnutls-dev zlib1g-dev liblua5.4-dev
#   libasound2-dev libao-dev libevdev-dev libudev-dev libpulse-dev
#   libzip-dev libchdr-dev libminiupnpc-dev libgl-dev libvulkan-dev
#
# To bump the upstream version:
#   1. Update UPSTREAM_VERSION + EXPECTED_COMMIT below
#   2. Update UPSTREAM_TAG + UPSTREAM_HASH in debian/rules to match
#   3. Add a debian/changelog entry: dch -v <NEW>-1foundry1 -D resolute "Bump to <NEW>"
#   4. Verify the commit SHA:
#        gh api repos/flyinghead/flycast/git/ref/tags/v<NEW> --jq .object.sha
#      dereferencing the tag object if it is annotated
#   5. Re-check debian/patches/ still applies (the version-override patch
#      touches CMakeLists.txt near the find_package(Git) block)

set -euo pipefail

for arg in "$@"; do
    case "$arg" in
        -h|--help)
            cat <<EOF
Build flycast as a Debian .deb via dpkg-buildpackage.

Usage: build.sh [-h|--help]

Environment overrides (rarely needed):
  FLYCAST_VERSION   upstream version without leading "v" (default: 2.6)
  FLYCAST_COMMIT    expected git commit SHA (must match version)

Note: Flycast statically links a large vendored dependency stack (glslang,
libchdr, libjuice, VulkanMemoryAllocator, ...) — expect on the order of
20-40 minutes and several GB of scratch space.

Output: \$REPO_ROOT/dist/flycast_<DEB_VERSION>_amd64.deb
EOF
            exit 0
            ;;
    esac
done

UPSTREAM_VERSION="${FLYCAST_VERSION:-2.6}"
EXPECTED_COMMIT="${FLYCAST_COMMIT:-392a429e8b040b3e5bf6696cb4f984274fc44123}"
TAG="v${UPSTREAM_VERSION}"
REPO_URL="https://github.com/flyinghead/flycast.git"

cd "$(dirname "$0")"
PKG_DIR="$(pwd)"
NAME="flycast"
REPO_ROOT="$(cd ../.. && pwd)"
mkdir -p "$REPO_ROOT/dist"

if ! curl -fsI -o /dev/null https://github.com/; then
    echo "ERROR: cannot reach github.com — skipping $NAME build" >&2
    exit 1
fi

echo "=== Installing Build-Depends ==="
if command -v apt-get >/dev/null; then
    _apt() { if [[ $EUID -eq 0 ]]; then apt-get "$@"; else sudo apt-get "$@"; fi; }
    _apt install -y --no-install-recommends \
        cmake pkgconf git \
        libsdl2-dev libcurl4-gnutls-dev zlib1g-dev liblua5.4-dev \
        libasound2-dev libao-dev libevdev-dev libudev-dev libpulse-dev \
        libzip-dev libchdr-dev libminiupnpc-dev libgl-dev libvulkan-dev
fi

WORKDIR=$(mktemp -d -t "${NAME}-build-XXXXXX")
# shellcheck disable=SC2064
trap "rm -rf '$WORKDIR'" EXIT

SRC_DIR="$WORKDIR/${NAME}-${UPSTREAM_VERSION}"

echo "=== Cloning $REPO_URL at $TAG ==="
git clone --depth 1 --branch "$TAG" "$REPO_URL" "$SRC_DIR"

echo "=== Verifying commit hash ==="
ACTUAL_COMMIT=$(git -C "$SRC_DIR" rev-parse HEAD)
if [[ "$ACTUAL_COMMIT" != "$EXPECTED_COMMIT" ]]; then
    echo "ERROR: commit hash mismatch for $TAG:" >&2
    echo "  expected: $EXPECTED_COMMIT" >&2
    echo "  actual:   $ACTUAL_COMMIT" >&2
    echo "Update EXPECTED_COMMIT in build.sh if the tag was moved." >&2
    exit 1
fi
echo "Commit verified: $ACTUAL_COMMIT"

echo "=== Initialising required submodules (depth 1) ==="
# Only the submodules a Linux desktop build actually reaches. Deliberately NOT
# fetched: SDL (system libsdl2-dev via -DUSE_HOST_SDL=ON), libchdr (system
# libchdr-dev via -DUSE_HOST_LIBCHDR=ON — see below), breakpad
# (-DUSE_BREAKPAD=OFF — a crash-dump uploader has no place in a distro
# package), discord-rpc (-DUSE_DISCORD=OFF), googletest (tests only), oboe and
# libadrenotools (Android), Syphon (macOS), Spout (Windows).
#
# libchdr is skipped for correctness, not just tidiness. Its vendored
# zstd-1.5.6 subproject builds a libzstd.a that is MISSING its common-module
# objects (xxhash.c, entropy_common.c), so the final link fails with undefined
# references to ZSTD_XXH64_*, FSE_readNCount and HUF_readStats from zstd's own
# compress objects. Ubuntu 26.04 ships libchdr as a proper shared library with
# a libchdr.pc, which is what -DUSE_HOST_LIBCHDR=ON consumes — that both fixes
# the link and satisfies Debian's preference for system libraries over
# vendored copies.
git -C "$SRC_DIR" submodule update --init --recursive --depth 1 \
    core/deps/Vulkan-Headers \
    core/deps/VulkanMemoryAllocator \
    core/deps/glslang \
    core/deps/libjuice \
    core/deps/luabridge \
    core/deps/rcheevos \
    core/deps/asio \
    core/deps/websocketpp \
    core/deps/xbyak \
    core/deps/libusb-cmake \
    core/deps/DreamPicoPort-API

echo "=== Verifying submodule gitlinks match the superproject tree ==="
# git checks this itself, but assert it explicitly so a silent shallow-fetch
# regression can never slip the pin.
FAILED=0
while read -r sha path; do
    [[ -d "$SRC_DIR/$path/.git" || -f "$SRC_DIR/$path/.git" ]] || continue
    actual=$(git -C "$SRC_DIR/$path" rev-parse HEAD)
    if [[ "$actual" != "$sha" ]]; then
        echo "ERROR: submodule $path is at $actual, expected $sha" >&2
        FAILED=1
    else
        echo "  ok  $path  $sha"
    fi
done < <(git -C "$SRC_DIR" ls-tree -r HEAD | awk '$2=="commit"{print $3, $4}')
[[ "$FAILED" -eq 0 ]] || { echo "ERROR: submodule pin verification failed" >&2; exit 1; }

echo "=== Stripping VCS metadata ==="
# The staged tree becomes the synthesised .orig tarball (see
# scripts/lib-source-build.sh), so the clone's object stores must not ride
# along — they are ~250 MB and carry no packaging value. Dropping .git is also
# why debian/rules injects GIT_VERSION/GIT_HASH explicitly.
find "$SRC_DIR" -maxdepth 4 -name .git -exec rm -rf {} + 2>/dev/null || true
rm -rf "$SRC_DIR/.github"

echo "=== Copying debian/ tree into source ==="
cp -a "$PKG_DIR/debian" "$SRC_DIR/"

echo "=== dpkg-buildpackage -us -uc -b ==="
# Emit the source package (.dsc + tarballs) -> dist/ for the apt Sources index
# (best-effort; never blocks the binary build below). See scripts/lib-source-build.sh.
if [[ -f "$REPO_ROOT/scripts/lib-source-build.sh" ]]; then
    # shellcheck source=/dev/null
    source "$REPO_ROOT/scripts/lib-source-build.sh"
    emit_source_package "$SRC_DIR" "$WORKDIR" "$REPO_ROOT" || true
fi
( cd "$SRC_DIR" && dpkg-buildpackage -us -uc -b )

DEB_VERSION=$(sed -n '1s/.*(\(.*\)).*/\1/p' "$PKG_DIR/debian/changelog")
# Architecture is fixed: the SH-4 dynarec upstream supports here is x86_64
# (Architecture: amd64).
DEB="$WORKDIR/${NAME}_${DEB_VERSION}_amd64.deb"
[[ -f "$DEB" ]] || {
    echo "ERROR: expected .deb not found: $DEB" >&2
    ls -la "$WORKDIR"
    exit 1
}

mv "$DEB" "$REPO_ROOT/dist/"
OUT="$REPO_ROOT/dist/$(basename "$DEB")"
echo "OK   $OUT  ($(stat -c%s "$OUT") bytes)"
